AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'CognitoTriggers

  Sample SAM Template for CognitoTriggers

  '
Globals:
  Function:
    Timeout: 3
Resources:
  CognitoTriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://kasaiso-cloudformation-templates-us-east-1/b4696a36db7307746d1f2e7ad604be69
      Handler: app.lambda_handler
      Runtime: python3.7
  CognitoTriggerFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName:
        Ref: CognitoTriggerFunction
      Principal: cognito-idp.amazonaws.com
Outputs:
  CognitoTriggerFunctionName:
    Description: CognitoTrigger
    Value:
      Ref: CognitoTriggerFunction
    Export:
      Name: CognitoTriggerFunctionName
  CognitoTriggerFunctionArn:
    Description: CognitoTrigger ARN
    Value:
      Fn::GetAtt:
      - CognitoTriggerFunction
      - Arn
    Export:
      Name: CognitoTriggerFunctionArn
