AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CognitoTriggers

  Sample SAM Template for CognitoTriggers

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CognitoTriggerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: triggers/
      Handler: app.lambda_handler
      Runtime: python3.7

  CognitoTriggerFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !Ref CognitoTriggerFunction
      Principal: cognito-idp.amazonaws.com

Outputs:
  CognitoTriggerFunctionName:
    Description: CognitoTrigger
    Value: !Ref CognitoTriggerFunction
    Export: 
      Name: CognitoTriggerFunctionName

  CognitoTriggerFunctionArn:
    Description: CognitoTrigger ARN
    Value: !GetAtt CognitoTriggerFunction.Arn
    Export: 
      Name: CognitoTriggerFunctionArn
